sample_app/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :users
  controller :users do
    get 'signup' => :new
  end

  controller :pages do
    get 'contact' => :contact
    get 'help' => :help
    get 'about' => :about
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

sample_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#
require 'bcrypt'
class User < ActiveRecord::Base
    has_secure_password
    attr_accessor :password, :password_confirmation,:remember_token

    validates_presence_of :password, :on => :create
    before_save { |user| user.email = email.downcase }


    REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: {with: REGEX_EMAIL}, uniqueness: { case_sensitive: false }
    validates :name, presence: true, length: {maximum: 30,minimum: 6}
    validates :password, presence: true, length: {maximum: 30,minimum: 6}, confirmation: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true

    # Encrypt password when create or set a new password
    def password=(pass)
      @password = pass
      unless pass.blank?
        self.password_digest = BCrypt::Password.create(pass)
      end
    end


    # Remembers a user in the database for use in persistent sessions.
    def remember
        @remember_token = User.new_token
        self.update_attribute(:remember_digest,User.digest(remember_token))
    end

    def forget
        self.update_attribute(:remember_digest,nil)
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    class << self
    # Returns the hash digest of the given string.
        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
        end

        # Returns a random token.
        def new_token
            SecureRandom.urlsafe_base64
        end
    end


end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

sample_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"

  end

  def about
    # @title = "About"

  end

  def hekp
    @title = "Help"
  end
end

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # debugger
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to current_user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end


  def current_user
    User.find_by(id: session[:user_id])
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by_id(params[:id])
    # exit
  end

  def edit
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)

    else
        render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

  public
    def create
      # debugger
      @user = User.new(user_params)
      puts request.method
      if @user.save

        flash[:success] = "Welcome to the Sample App!"
        redirect_to user_url(@user)
      else
          render 'new'
      end

  end


end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

  # Return a page title
  def full_title(title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if title.nil?
      base_title
    else
      "#{base_title} | #{title}"
    end
  end


end

sample_app/app/helpers/pages_helper.rb
module PagesHelper

end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper

    # Save user information through session when user login page
    def log_in(user)
        session[:user_id] = user.id
    end

    # Delete user information through session when user logout page

    def log_out
        self.forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end


    # return user information if it exitst for using it in views/template

    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end



    def logged_in?
        !current_user.nil?
    end

    #Save session_id and token into Cookies
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    #Remove session_id and token stored by Cookies
    def forget(user)
        user.forget
        cookies.delete(:remember_token)
        cookies.delete(:user_id)
    end

end

sample_app/app/helpers/users_helper.rb
module UsersHelper

    # Return a image from gravatar by email
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

sample_app/app/views/layouts/_footer.html.erb
<footer>
  <nav class="footet">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="navbar-inner">
    <div>
  <% logo = image_tag('rails.png', :alt => "Sample App", :class => "round") %>
  <%= link_to logo, root_path %>

  <nav>
    <ul class="pull-right accounts">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to "Log in", login_path %></li>
      <% end %>

    </ul>
  </nav>
    </div>
    </div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-info">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |mes| %>
        <li><%= mes %></li>
        <%end%>
      </ul>
    </div>
<%end%>

sample_app/app/views/users/destroy.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

sample_app/app/views/users/edit.html.erb
<% provide(:title,'Edit') %>

<h1>Update your profiles</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages' %>
    <%= form_for(@user) do |f| %>
        <%= f.label 'Username'%>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

sample_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>